title: Learn some Python with Jordan and Jacky
description: A gallery of short videos to get started with Python.
theme: just-the-docs

url: https://datacentricdesign.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
